spring.profiles.active: dev
server.servlet.session.cookie.name: AJANTHASESSION
server.servlet.context-path: /a

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
      
server:
  port: 8181