logging.level.org.springframework.jdbc.core: trace
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring.mvc.view.prefix: WEB-INF/jsp/
spring.mvc.view.suffix: .jsp
pdf.location: C:\\Users\\kumaran\\Downloads\\
recipient: priyasathiya48@gmail.com
cc.recipient: kumaranwip@gmail.com 
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: false
spring.datasource.initialize: true
web:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
    allowed-headers: "Access-Control-Allow-Origin"
    exposed-headers: "X-Get-Header"
spring:
  config:
    activate:
      on-profile: dev
  mail:
        host: smtp.gmail.com
        password: aahgcbnsfwsuoipu
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        username: kumaranvec2789@gmail.com

  datasource:
    initialization-mode: never
datasource:
  db-pdf:
    jdbc-url: jdbc:postgresql://72.167.46.93:5432/oxford
    username: myadmin
    password: Trytry@123!!!!
    driver-class-name: org.postgresql.Driver
    hibernate.hbm2ddl.auto:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    
jwt:
  secret: InhouseApplicationsecretkeyInhouseApplicationsecretkeyInhouseApplicationsecretkeyInhouseApplicationsecretkeyInhouseApplicationsecretkey
  expire-length: 1440 # minutes: 60x24